### ISSUE TITLE
init_llm(...) does not work in 7.2.0

### ISSUE THREAD

**Issue by zhaoyang868686** [SAP/ai-sdk-python#111]
### Checklist

- [x] My issue is not an [AI Core service issue](https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/support-process), but an SDK issue.
- [x] My issue is a Python related issue, not a [JS/TS](https://github.com/SAP/ai-sdk-js/issues) or [Java](https://github.com/SAP/ai-sdk-java/issues) related issue.
- [x] My issue is not [already reported or documented](https://github.com/SAP/ai-sdk-python/issues).

### Describe the Bug

https://help.sap.com/doc/generative-ai-hub-sdk/CLOUD/en-US/_reference/gen_ai_hub.html#harmonized-model-initialization

It seems that init_llm(...) works as expected with Python SDK 6.10.0, but no longer works with 7.2.0.

### Steps to Reproduce

1. Setup Python SDK 7.2.0
2. Try init_llm(...) with this [example](https://help.sap.com/doc/generative-ai-hub-sdk/CLOUD/en-US/_reference/gen_ai_hub.html#harmonized-model-initialization).
3. An error occurred while initializing the LLM: 'NoneType' object has no attribute 'deployment_class'.

### Expected Behavior

An error occurred while initializing the LLM: 'NoneType' object has no attribute 'deployment_class'.

### Used Versions

Python SDK 7.2.0

### Region

Not listed above

### Affected Development Phase

Development

### Impact

No Impact

**Comment by yamaceay** [comment]
Good point, the docs are wrong. Also mentioned here SAP/ai-sdk-python-backlog#7, quoting here

> LangchainIntegration.HarmonizedModelInitialization[0]: In the underlying subclass call, proxy client is forwarded as None, so that we run into the error NoneType has no such XXX attribute / property. For this, we should always instantiate proxy client using gen_ai_hub.proxy.core.get_proxy_client(), and maybe, it makes more sense to switch to a cheaper and more reliable model, e.g., gpt-4o, since I received empty string as a response of calling with gpt-5-nano.

**Comment by zhaoyang868686** [comment]
> init_llm(..., proxy_client=proxy_client, ...)

In version 6.10.0, init_llm() could be called without any arguments.

This is an incompatible change from the user's perspective, as existing code that worked with 6.10.0 may no longer work after upgrading to 7.2.0.

We should explicitly mention this change in the release notes so users understand why their existing code may stop working after the upgrade and know how to update it.

**Comment by yamaceay** [comment]
Linking the current PR: SAP/ai-sdk-python#125

**Comment by alpkom** [comment]
To clarify a few points, so that there are no confusions...

First of all, calling init_llm() with no arguments at all, wouldn't work even with previous version. How is the SDK supposed to now which model to initialize? So there is no change there.
@zhaoyang868686 can you give me an example where init_llm() is supposed to work with no arguments at all?

What did work before was that the user didn't have to provide a proxy_client. Which gets us to second point. This wasn't intentional, so it's a bug not a breaking change. A fix for that is already being provided.

**Comment by zhaoyang868686** [comment]
> To clarify a few points, so that there are no confusions...
> 
> First of all, calling init_llm() with no arguments at all, wouldn't work even with previous version. How is the SDK supposed to now which model to initialize? So there is no change there. [@zhaoyang868686](https://github.com/zhaoyang868686) can you give me an example where init_llm() is supposed to work with no arguments at all?
> 
> What did work before was that the user didn't have to provide a proxy_client. Which gets us to second point. This wasn't intentional, so it's a bug not a breaking change. A fix for that is already being provided.

Sorry for the confusion. I wasn't referring to `init_llm()` with no arguments.

What I meant is that `init_llm(model_name="...", ...)` worked in version 6.10.0, but stopped working after upgrading to 7.2.0.

Starting from 7.2.0, it seems that a `proxy_client` needs to be explicitly provided when calling `init_llm()`. This requirement wasn't documented or otherwise communicated, so from the user's perspective, the existing code simply stopped working after the upgrade, without an obvious indication of how it should be fixed.

Whether this should be classified as a bug or a breaking change is ultimately up to the development team.

Thanks for clarifying that this was unintentional and that a fix is already being provided.
